/etc/caddy/caddyfile now is generated when the container is started using templates from /opt/daspanel/conf-templates/etc/caddy/caddyfile.tmpl and ENV variables.

diff --git a/rootfs/etc/cont-init.d/50-00-caddy b/rootfs/etc/cont-init.d/50-00-caddy
--- a/rootfs/etc/cont-init.d/50-00-caddy
+++ b/rootfs/etc/cont-init.d/50-00-caddy
@@ -1,5 +1,13 @@
 #!/usr/bin/with-contenv sh
 
+# Master admin email must be informed
+if [ -z "$DASPANEL_HOST" ]; then
+    echo "***"
+    echo "ERROR: You must set the env variable DASPANEL_HOST to a valid value"
+    echo "***"
+    exit 1
+fi
+
 log() {
   if [[ "$@" ]]; then echo "[`date +'%Y-%m-%d %T'`] $@";
   else echo; fi
@@ -36,4 +44,8 @@ fi
 ln -sf /opt/daspanel/data/$DASPANEL_GUUID/conf/caddy/etc/caddy/sites-available /etc/caddy/sites-available
 ln -sf /opt/daspanel/data/$DASPANEL_GUUID/conf/caddy/etc/caddy/sites-enabled /etc/caddy/sites-enabled
 
+# Configure caddy
+/usr/bin/templater -d \
+  -o /etc/caddy/caddyfile \
+  /opt/daspanel/conf-templates/etc/caddy/caddyfile.tmpl
 
